### ISSUE TITLE
Some parts of the styling aren't working

### ISSUE THREAD

**Issue by RoseIlanga** [cainy-a/Diskai#5]
I think the big Discord update recently broke a lot of things, themes included, because they renamed a lot of elements. I don't know exactly what needs changing, but a lot of the colouring, including all of the text stuff, seems to be broken.

Thank you for making the theme, by the way! I've been enjoying it.

**Comment by yellowsink** [comment]
Thanks for reminding me about this, I'll fix it soon, just busy recently =w=

**Comment by RoseIlanga** [comment]
No problem. It's no rush, for me at least. It seems like a lot of others' themes are in the same position. And I know the Discord update broke a lot of client mods and plugins too, which you're probably also having to contend with.

**Comment by yellowsink** [comment]
Fixed in 2c56dea
