### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by MaverickEsq** [cainy-a/Diskai#6]
Hi,
Apologies if I'm just not getting it but how do I install this theme? I tried with BetterDiscord and RePlugged but neither seemed to like it, I followed the steps in [.github](https://github.com/yellowsink/Diskai/tree/master/.github)/[workflows](https://github.com/yellowsink/Diskai/tree/master/.github/workflows)/[deploy.yml](https://github.com/yellowsink/Diskai/tree/master/.github/workflows/deploy.yaml) to create a new diskai.theme.css but BD said there was no manifest and RP just showed nothing. Where am I going wrong here?

**Comment by yellowsink** [comment]
Ah yes, at the minute the theme does not have a better discord compatible manifest.
I will add one when I get around to it but for now it works fine on shelter.

I mostly haven't touched this to be honest (hence also shipping manifests for vitality and powercord both of which are long gone)
Thanks for bringing this to my attention, and you're doing nothing wrong ;)

**Comment by MaverickEsq** [comment]
Awesome! That's the breadcrumb I need, if only I had done as your bio suggests and checked out uwu network.

For those who found this whilst trying to install it:

1. Install shelter: https://github.com/uwu/shelter
2. Install snazzy shelter by pasting this into the add plugin url field: https://yellowsink.github.io/shelter-plugins/snazzy-shelter/
(It will not work in browser)
3. You now have a themes tab, add it there.

Thank you, and thanks for the theme, I love it.

**Comment by yellowsink** [comment]
No problem, glad you like the theme! Hope you enjoy shelter, I'm very proud of it ;)
